name: Cross-Platform CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [g++, clang++, cl]
        exclude:
          - os: windows-latest
            compiler: clang++
          - os: macos-latest
            compiler: cl
          - os: ubuntu-latest
            compiler: cl  # Excluir `cl` en Ubuntu

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash  # Usamos bash en todos los OS
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          if [ "${{ matrix.compiler }}" = "clang++" ]; then
            sudo apt-get install -y clang
          fi
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          brew update
          brew install cmake --formula
          if [ "${{ matrix.compiler }}" = "clang++" ]; then
            brew install llvm
          fi
        fi

    - name: Create build directory
      shell: bash  # Aseguramos que todos los pasos sean bash
      run: mkdir build

    - name: Set up Visual Studio Build Tools
      if: runner.os == 'Windows'
      run: |
        choco install visualstudio2019buildtools --version 16.11.8 -y
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Configure CMake
      shell: bash  # Usamos bash en todos los OS
      run: |
        cd build
        if [ "${{ runner.os }}" = "Windows" ]; then
          cmake .. -G "Visual Studio 17 2022" -A x64
        else
          cmake .. -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        fi

    - name: Build project
      shell: bash  # Usamos bash en todos los OS
      run: |
        cd build
        cmake --build . --config Release

    - name: Verify executable
      shell: bash  # Aseguramos que todos los pasos sean bash
      run: |
        cd build
        if [ "${{ runner.os }}" = "Windows" ]; then
          if [ ! -f "Release/ToDoApp.exe" ]; then echo "Windows executable missing!"; exit 1; fi
        else
          if [ ! -f "ToDoApp" ]; then echo "Executable missing!"; exit 1; fi
        fi
